version: '3.8'

services:
  # Spring Application
  book-rental:
    build: ../book-rental
    ports:
      - "8080:8080"
    networks:
      - application-network
    depends_on:
      - book-rental-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://book-rental-db:3306/book_rental_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123

  # MySQL Database
  book-rental-db:
    image: mysql:8.0
    container_name: book-rental-db-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: book_rental_db
    volumes:
      - ./persistence:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - application-network
    ports:
      - "3316:3316"

# Angular Frontend
  book-rental-frontend:
    build: ../book-rental-front
    networks:
      - application-network
    depends_on:
      - book-rental
    ports:
      - "4200:80"

# Volumes for MySQL data persistence
volumes:
  mysql-data:

# Networks to make sure both services can see each other
networks:
  application-network:
    driver: bridge
